### ISSUE TITLE
add email service

### ISSUE THREAD

**Issue by VikramTiwari** [VikramTiwari/webstack#12]
- [x] let background jobs handle the email

**Comment by Mokanarangan** [comment]
This can be achieved by using the nodemailer. Do you want to use that or platform specific api..??

**Comment by VikramTiwari** [comment]
There's a commit already present in the vikram/app-server branch. Debugging
that. It's using Sparkpost's service and package.

**Comment by VikramTiwari** [comment]
Email by SparkPost: https://github.com/VikramTiwari/webstack/commit/ea502b1d528c80331dd2be6c50614c37a2228db4
