### ISSUE TITLE
User API

### ISSUE THREAD

**Issue by VikramTiwari** [VikramTiwari/webstack#15]
- [x] DB Model
- [x] Auth and Tokens
- [x] Login
- [x] Signup
- [x] GET
- [x] PUT

**Comment by raj-subhankar** [comment]
@VikramTiwari what are the fields you want for the user model?

**Comment by VikramTiwari** [comment]
@raj-subhankar It's already under active development. Please find the issues with no assignees.

**Comment by VikramTiwari** [comment]
Basic User API: https://github.com/VikramTiwari/webstack/commit/b3477419b868e7b1583ccc9527d663960fde864a
